// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ActiveRecord struct {
	ID          int64
	Date        string
	AmountCents int64
	CurrencyID  int64
	Notes       string
	CreatedAt   int64
	CreatedBy   int64
	UpdatedAt   int64
	UpdatedBy   int64
	DeletedAt   sql.NullInt64
	DeletedBy   sql.NullInt64
}

type ActiveTag struct {
	ID          int64
	Name        string
	Description string
	Notes       string
	CreatedAt   int64
	CreatedBy   int64
	UpdatedAt   int64
	UpdatedBy   int64
	DeletedAt   sql.NullInt64
	DeletedBy   sql.NullInt64
}

type ActiveUser struct {
	ID        int64
	Username  string
	CreatedAt int64
	UpdatedAt int64
	DeletedAt sql.NullInt64
	DeletedBy sql.NullInt64
}

type Currency struct {
	ID        int64
	Code      string
	CreatedAt int64
	UpdatedAt int64
}

type PinnedTag struct {
	TagID     int64
	Position  int64
	CreatedAt int64
	CreatedBy int64
	UpdatedAt int64
	UpdatedBy int64
}

type Record struct {
	ID          int64
	Date        string
	AmountCents int64
	CurrencyID  int64
	Notes       string
	CreatedAt   int64
	CreatedBy   int64
	UpdatedAt   int64
	UpdatedBy   int64
	DeletedAt   sql.NullInt64
	DeletedBy   sql.NullInt64
}

type RecordLink struct {
	ParentID  int64
	ChildID   int64
	CreatedAt int64
	CreatedBy int64
}

type RecordsTag struct {
	RecordID  int64
	TagID     int64
	CreatedAt int64
	CreatedBy int64
	UpdatedAt int64
	UpdatedBy int64
}

type Tag struct {
	ID          int64
	Name        string
	Description string
	Notes       string
	CreatedAt   int64
	CreatedBy   int64
	UpdatedAt   int64
	UpdatedBy   int64
	DeletedAt   sql.NullInt64
	DeletedBy   sql.NullInt64
}

type User struct {
	ID        int64
	Username  string
	CreatedAt int64
	UpdatedAt int64
	DeletedAt sql.NullInt64
	DeletedBy sql.NullInt64
}
