// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record_links.sql

package db

import (
	"context"
	"strings"
)

const addRecordLink = `-- name: AddRecordLink :exec
INSERT INTO record_links (parent_id, child_id, created_at, created_by)
VALUES (?, ?, ?, ?)
`

type AddRecordLinkParams struct {
	ParentID  int64
	ChildID   int64
	CreatedAt int64
	CreatedBy int64
}

func (q *Queries) AddRecordLink(ctx context.Context, arg AddRecordLinkParams) error {
	_, err := q.db.ExecContext(ctx, addRecordLink,
		arg.ParentID,
		arg.ChildID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const getRecordChildren = `-- name: GetRecordChildren :many
SELECT r.id, r.date, r.amount_cents, r.currency_id, r.notes, r.created_at, r.created_by, r.updated_at, r.updated_by, r.deleted_at, r.deleted_by FROM active_records r
INNER JOIN record_links rl ON r.id = rl.child_id
WHERE rl.parent_id = ?
ORDER BY r.date DESC, r.id DESC
`

func (q *Queries) GetRecordChildren(ctx context.Context, parentID int64) ([]ActiveRecord, error) {
	rows, err := q.db.QueryContext(ctx, getRecordChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveRecord
	for rows.Next() {
		var i ActiveRecord
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.CurrencyID,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordParents = `-- name: GetRecordParents :many
SELECT r.id, r.date, r.amount_cents, r.currency_id, r.notes, r.created_at, r.created_by, r.updated_at, r.updated_by, r.deleted_at, r.deleted_by FROM active_records r
INNER JOIN record_links rl ON r.id = rl.parent_id
WHERE rl.child_id = ?
ORDER BY r.date DESC, r.id DESC
`

func (q *Queries) GetRecordParents(ctx context.Context, childID int64) ([]ActiveRecord, error) {
	rows, err := q.db.QueryContext(ctx, getRecordParents, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveRecord
	for rows.Next() {
		var i ActiveRecord
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.CurrencyID,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordTagsByIDs = `-- name: GetRecordTagsByIDs :many
SELECT rt.record_id, t.name FROM tags t
INNER JOIN records_tags rt ON t.id = rt.tag_id
WHERE rt.record_id IN (/*SLICE:record_ids*/?)
ORDER BY rt.record_id, t.name
`

type GetRecordTagsByIDsRow struct {
	RecordID int64
	Name     string
}

func (q *Queries) GetRecordTagsByIDs(ctx context.Context, recordIds []int64) ([]GetRecordTagsByIDsRow, error) {
	query := getRecordTagsByIDs
	var queryParams []interface{}
	if len(recordIds) > 0 {
		for _, v := range recordIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:record_ids*/?", strings.Repeat(",?", len(recordIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:record_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecordTagsByIDsRow
	for rows.Next() {
		var i GetRecordTagsByIDsRow
		if err := rows.Scan(&i.RecordID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecordLink = `-- name: RemoveRecordLink :exec
DELETE FROM record_links WHERE parent_id = ? AND child_id = ?
`

type RemoveRecordLinkParams struct {
	ParentID int64
	ChildID  int64
}

func (q *Queries) RemoveRecordLink(ctx context.Context, arg RemoveRecordLinkParams) error {
	_, err := q.db.ExecContext(ctx, removeRecordLink, arg.ParentID, arg.ChildID)
	return err
}

const searchParentCandidates = `-- name: SearchParentCandidates :many
SELECT DISTINCT r.id, r.date, r.amount_cents, r.currency_id, r.notes
FROM active_records r
WHERE r.date BETWEEN ? AND ?
  AND r.currency_id = ?
  AND r.id != ?
ORDER BY r.date DESC, r.id DESC
`

type SearchParentCandidatesParams struct {
	Date       string
	Date_2     string
	CurrencyID int64
	ID         int64
}

type SearchParentCandidatesRow struct {
	ID          int64
	Date        string
	AmountCents int64
	CurrencyID  int64
	Notes       string
}

func (q *Queries) SearchParentCandidates(ctx context.Context, arg SearchParentCandidatesParams) ([]SearchParentCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchParentCandidates,
		arg.Date,
		arg.Date_2,
		arg.CurrencyID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchParentCandidatesRow
	for rows.Next() {
		var i SearchParentCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.CurrencyID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
