// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records_tags.sql

package db

import (
	"context"
)

const addRecordTag = `-- name: AddRecordTag :exec
INSERT INTO records_tags (record_id, tag_id, created_at, created_by, updated_at, updated_by)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddRecordTagParams struct {
	RecordID  int64
	TagID     int64
	CreatedAt int64
	CreatedBy int64
	UpdatedAt int64
	UpdatedBy int64
}

func (q *Queries) AddRecordTag(ctx context.Context, arg AddRecordTagParams) error {
	_, err := q.db.ExecContext(ctx, addRecordTag,
		arg.RecordID,
		arg.TagID,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const getRecordTags = `-- name: GetRecordTags :many
SELECT t.id, t.name, t.description, t.notes, t.created_at, t.created_by, t.updated_at, t.updated_by, t.deleted_at, t.deleted_by FROM tags t
INNER JOIN records_tags rt ON t.id = rt.tag_id
WHERE rt.record_id = ?
ORDER BY t.name
`

func (q *Queries) GetRecordTags(ctx context.Context, recordID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getRecordTags, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagRecords = `-- name: GetTagRecords :many
SELECT r.id, r.date, r.amount_cents, r.currency_id, r.notes, r.created_at, r.created_by, r.updated_at, r.updated_by, r.deleted_at, r.deleted_by FROM records r
INNER JOIN records_tags rt ON r.id = rt.record_id
WHERE rt.tag_id = ?
ORDER BY r.date DESC, r.id DESC
`

func (q *Queries) GetTagRecords(ctx context.Context, tagID int64) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, getTagRecords, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.CurrencyID,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllRecordTags = `-- name: RemoveAllRecordTags :exec
DELETE FROM records_tags WHERE record_id = ?
`

func (q *Queries) RemoveAllRecordTags(ctx context.Context, recordID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllRecordTags, recordID)
	return err
}

const removeAllTagRecords = `-- name: RemoveAllTagRecords :exec
DELETE FROM records_tags WHERE tag_id = ?
`

func (q *Queries) RemoveAllTagRecords(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllTagRecords, tagID)
	return err
}

const removeRecordTag = `-- name: RemoveRecordTag :exec
DELETE FROM records_tags WHERE record_id = ? AND tag_id = ?
`

type RemoveRecordTagParams struct {
	RecordID int64
	TagID    int64
}

func (q *Queries) RemoveRecordTag(ctx context.Context, arg RemoveRecordTagParams) error {
	_, err := q.db.ExecContext(ctx, removeRecordTag, arg.RecordID, arg.TagID)
	return err
}
