// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package db

import (
	"context"
	"database/sql"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateRecordParams struct {
	Date        string
	AmountCents int64
	CurrencyID  int64
	Notes       string
	CreatedAt   int64
	CreatedBy   int64
	UpdatedAt   int64
	UpdatedBy   int64
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.Date,
		arg.AmountCents,
		arg.CurrencyID,
		arg.Notes,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.AmountCents,
		&i.CurrencyID,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM records WHERE id = ?
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.AmountCents,
		&i.CurrencyID,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const hardDeleteRecord = `-- name: HardDeleteRecord :exec
DELETE FROM records WHERE id = ?
`

func (q *Queries) HardDeleteRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteRecord, id)
	return err
}

const listActiveRecords = `-- name: ListActiveRecords :many
SELECT id, date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM active_records ORDER BY date DESC, id DESC
`

func (q *Queries) ListActiveRecords(ctx context.Context) ([]ActiveRecord, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveRecord
	for rows.Next() {
		var i ActiveRecord
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.CurrencyID,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRecordsByDateRange = `-- name: ListActiveRecordsByDateRange :many
SELECT id, date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM active_records
WHERE date BETWEEN ? AND ?
ORDER BY date DESC, id DESC
`

type ListActiveRecordsByDateRangeParams struct {
	FromDate string
	ToDate   string
}

func (q *Queries) ListActiveRecordsByDateRange(ctx context.Context, arg ListActiveRecordsByDateRangeParams) ([]ActiveRecord, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRecordsByDateRange, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveRecord
	for rows.Next() {
		var i ActiveRecord
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.CurrencyID,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT id, date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM records ORDER BY date DESC, id DESC
`

func (q *Queries) ListRecords(ctx context.Context) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.CurrencyID,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreRecord = `-- name: RestoreRecord :one
UPDATE records
SET deleted_at = NULL, deleted_by = NULL
WHERE id = ?
RETURNING id, date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

func (q *Queries) RestoreRecord(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRowContext(ctx, restoreRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.AmountCents,
		&i.CurrencyID,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteRecord = `-- name: SoftDeleteRecord :exec
UPDATE records
SET deleted_at = ?, deleted_by = ?
WHERE id = ?
`

type SoftDeleteRecordParams struct {
	DeletedAt sql.NullInt64
	DeletedBy sql.NullInt64
	ID        int64
}

func (q *Queries) SoftDeleteRecord(ctx context.Context, arg SoftDeleteRecordParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteRecord, arg.DeletedAt, arg.DeletedBy, arg.ID)
	return err
}

const updateRecord = `-- name: UpdateRecord :one
UPDATE records
SET date = ?, amount_cents = ?, currency_id = ?, notes = ?, updated_at = ?, updated_by = ?
WHERE id = ?
RETURNING id, date, amount_cents, currency_id, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateRecordParams struct {
	Date        string
	AmountCents int64
	CurrencyID  int64
	Notes       string
	UpdatedAt   int64
	UpdatedBy   int64
	ID          int64
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, updateRecord,
		arg.Date,
		arg.AmountCents,
		arg.CurrencyID,
		arg.Notes,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.AmountCents,
		&i.CurrencyID,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
