// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createSavedQuery = `-- name: CreateSavedQuery :one
INSERT INTO saved_queries (name, date_from, date_to, currency_id, fuzzy_text, created_at, created_by, updated_at, updated_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, date_from, date_to, currency_id, fuzzy_text, created_at, created_by, updated_at, updated_by
`

type CreateSavedQueryParams struct {
	Name       string
	DateFrom   string
	DateTo     string
	CurrencyID sql.NullInt64
	FuzzyText  string
	CreatedAt  int64
	CreatedBy  int64
	UpdatedAt  int64
	UpdatedBy  int64
}

func (q *Queries) CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (SavedQuery, error) {
	row := q.db.QueryRowContext(ctx, createSavedQuery,
		arg.Name,
		arg.DateFrom,
		arg.DateTo,
		arg.CurrencyID,
		arg.FuzzyText,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateFrom,
		&i.DateTo,
		&i.CurrencyID,
		&i.FuzzyText,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteSavedQuery = `-- name: DeleteSavedQuery :exec
DELETE FROM saved_queries WHERE id = ?
`

func (q *Queries) DeleteSavedQuery(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSavedQuery, id)
	return err
}

const getSavedQuery = `-- name: GetSavedQuery :one
SELECT id, name, date_from, date_to, currency_id, fuzzy_text, created_at, created_by, updated_at, updated_by FROM saved_queries WHERE id = ?
`

func (q *Queries) GetSavedQuery(ctx context.Context, id int64) (SavedQuery, error) {
	row := q.db.QueryRowContext(ctx, getSavedQuery, id)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateFrom,
		&i.DateTo,
		&i.CurrencyID,
		&i.FuzzyText,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listSavedQueries = `-- name: ListSavedQueries :many
SELECT id, name, date_from, date_to, currency_id, fuzzy_text, created_at, created_by, updated_at, updated_by FROM saved_queries ORDER BY name
`

func (q *Queries) ListSavedQueries(ctx context.Context) ([]SavedQuery, error) {
	rows, err := q.db.QueryContext(ctx, listSavedQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedQuery
	for rows.Next() {
		var i SavedQuery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DateFrom,
			&i.DateTo,
			&i.CurrencyID,
			&i.FuzzyText,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedQuery = `-- name: UpdateSavedQuery :one
UPDATE saved_queries
SET name = ?, date_from = ?, date_to = ?, currency_id = ?, fuzzy_text = ?, updated_at = ?, updated_by = ?
WHERE id = ?
RETURNING id, name, date_from, date_to, currency_id, fuzzy_text, created_at, created_by, updated_at, updated_by
`

type UpdateSavedQueryParams struct {
	Name       string
	DateFrom   string
	DateTo     string
	CurrencyID sql.NullInt64
	FuzzyText  string
	UpdatedAt  int64
	UpdatedBy  int64
	ID         int64
}

func (q *Queries) UpdateSavedQuery(ctx context.Context, arg UpdateSavedQueryParams) (SavedQuery, error) {
	row := q.db.QueryRowContext(ctx, updateSavedQuery,
		arg.Name,
		arg.DateFrom,
		arg.DateTo,
		arg.CurrencyID,
		arg.FuzzyText,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DateFrom,
		&i.DateTo,
		&i.CurrencyID,
		&i.FuzzyText,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
