// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_query_tags.sql

package db

import (
	"context"
)

const addSavedQueryTag = `-- name: AddSavedQueryTag :exec
INSERT INTO saved_query_tags (query_id, tag_id) VALUES (?, ?)
`

type AddSavedQueryTagParams struct {
	QueryID int64
	TagID   int64
}

func (q *Queries) AddSavedQueryTag(ctx context.Context, arg AddSavedQueryTagParams) error {
	_, err := q.db.ExecContext(ctx, addSavedQueryTag, arg.QueryID, arg.TagID)
	return err
}

const listSavedQueryTags = `-- name: ListSavedQueryTags :many
SELECT t.id, t.name, t.description, t.notes, t.created_at, t.created_by, t.updated_at, t.updated_by, t.deleted_at, t.deleted_by FROM tags t
INNER JOIN saved_query_tags sqt ON t.id = sqt.tag_id
WHERE sqt.query_id = ?
ORDER BY t.name
`

func (q *Queries) ListSavedQueryTags(ctx context.Context, queryID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listSavedQueryTags, queryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllSavedQueryTags = `-- name: RemoveAllSavedQueryTags :exec
DELETE FROM saved_query_tags WHERE query_id = ?
`

func (q *Queries) RemoveAllSavedQueryTags(ctx context.Context, queryID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllSavedQueryTags, queryID)
	return err
}

const removeSavedQueryTag = `-- name: RemoveSavedQueryTag :exec
DELETE FROM saved_query_tags WHERE query_id = ? AND tag_id = ?
`

type RemoveSavedQueryTagParams struct {
	QueryID int64
	TagID   int64
}

func (q *Queries) RemoveSavedQueryTag(ctx context.Context, arg RemoveSavedQueryTagParams) error {
	_, err := q.db.ExecContext(ctx, removeSavedQueryTag, arg.QueryID, arg.TagID)
	return err
}
