// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
	"database/sql"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, description, notes, created_at, created_by, updated_at, updated_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateTagParams struct {
	Name        string
	Description string
	Notes       string
	CreatedAt   int64
	CreatedBy   int64
	UpdatedAt   int64
	UpdatedBy   int64
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.Name,
		arg.Description,
		arg.Notes,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, name, description, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, description, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const hardDeleteTag = `-- name: HardDeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) HardDeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteTag, id)
	return err
}

const listActiveTags = `-- name: ListActiveTags :many
SELECT id, name, description, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM active_tags ORDER BY name
`

func (q *Queries) ListActiveTags(ctx context.Context) ([]ActiveTag, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveTag
	for rows.Next() {
		var i ActiveTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, description, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Notes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTag = `-- name: RestoreTag :one
UPDATE tags
SET deleted_at = NULL, deleted_by = NULL
WHERE id = ?
RETURNING id, name, description, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

func (q *Queries) RestoreTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, restoreTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteTag = `-- name: SoftDeleteTag :exec
UPDATE tags
SET deleted_at = ?, deleted_by = ?
WHERE id = ?
`

type SoftDeleteTagParams struct {
	DeletedAt sql.NullInt64
	DeletedBy sql.NullInt64
	ID        int64
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTag, arg.DeletedAt, arg.DeletedBy, arg.ID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = ?, description = ?, notes = ?, updated_at = ?, updated_by = ?
WHERE id = ?
RETURNING id, name, description, notes, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateTagParams struct {
	Name        string
	Description string
	Notes       string
	UpdatedAt   int64
	UpdatedBy   int64
	ID          int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.Name,
		arg.Description,
		arg.Notes,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Notes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
