// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: targets.sql

package db

import (
	"context"
)

const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (name, saved_query_id, target_cents, created_at, created_by, updated_at, updated_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, saved_query_id, target_cents, created_at, created_by, updated_at, updated_by
`

type CreateTargetParams struct {
	Name         string
	SavedQueryID int64
	TargetCents  int64
	CreatedAt    int64
	CreatedBy    int64
	UpdatedAt    int64
	UpdatedBy    int64
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, createTarget,
		arg.Name,
		arg.SavedQueryID,
		arg.TargetCents,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SavedQueryID,
		&i.TargetCents,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM targets WHERE id = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTarget, id)
	return err
}

const getTarget = `-- name: GetTarget :one
SELECT id, name, saved_query_id, target_cents, created_at, created_by, updated_at, updated_by FROM targets WHERE id = ?
`

func (q *Queries) GetTarget(ctx context.Context, id int64) (Target, error) {
	row := q.db.QueryRowContext(ctx, getTarget, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SavedQueryID,
		&i.TargetCents,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listTargets = `-- name: ListTargets :many
SELECT id, name, saved_query_id, target_cents, created_at, created_by, updated_at, updated_by FROM targets ORDER BY created_at ASC
`

func (q *Queries) ListTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, listTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SavedQueryID,
			&i.TargetCents,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTarget = `-- name: UpdateTarget :one
UPDATE targets
SET name = ?, saved_query_id = ?, target_cents = ?, updated_at = ?, updated_by = ?
WHERE id = ?
RETURNING id, name, saved_query_id, target_cents, created_at, created_by, updated_at, updated_by
`

type UpdateTargetParams struct {
	Name         string
	SavedQueryID int64
	TargetCents  int64
	UpdatedAt    int64
	UpdatedBy    int64
	ID           int64
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, updateTarget,
		arg.Name,
		arg.SavedQueryID,
		arg.TargetCents,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SavedQueryID,
		&i.TargetCents,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
