// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, created_at, updated_at)
VALUES (?, ?, ?)
RETURNING id, username, created_at, updated_at, deleted_at, deleted_by
`

type CreateUserParams struct {
	Username  string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.CreatedAt, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, created_at, updated_at, deleted_at, deleted_by FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, created_at, updated_at, deleted_at, deleted_by FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) HardDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteUser, id)
	return err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, username, created_at, updated_at, deleted_at, deleted_by FROM active_users ORDER BY id
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]ActiveUser, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveUser
	for rows.Next() {
		var i ActiveUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, created_at, updated_at, deleted_at, deleted_by FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET deleted_at = NULL, deleted_by = NULL
WHERE id = ?
RETURNING id, username, created_at, updated_at, deleted_at, deleted_by
`

func (q *Queries) RestoreUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, restoreUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = ?, deleted_by = ?
WHERE id = ?
`

type SoftDeleteUserParams struct {
	DeletedAt sql.NullInt64
	DeletedBy sql.NullInt64
	ID        int64
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, arg.DeletedAt, arg.DeletedBy, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = ?, updated_at = ?
WHERE id = ?
RETURNING id, username, created_at, updated_at, deleted_at, deleted_by
`

type UpdateUserParams struct {
	Username  string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
